### ISSUE TITLE
Even older version

### ISSUE THREAD

**Issue by jeremymeyers** [andyjonesx/WLSXX-Wrestling-League-Simluator#1]
Hey I happen to have WLS  version 2.0 from 1993 (found it in an old backup). If that would be of interest, i'm happy to email it.

**Comment by vannityv** [comment]
Hey. That would be awesome - we can keep it here for archival purposes!

**Comment by vannityv** [comment]
Either email it to me (andyjonesx-at-gmail) or do a pull request.

**Comment by vannityv** [comment]
Added
